NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Controllers/SiteController.cs
// <copyright file="SiteController.cs" company="ZZCompanyNameZZ">
// Copyright (c) ZZCompanyNameZZ. All rights reserved.
// </copyright>

namespace $safeprojectname$.Controllers
{
    using BIA.Net.Business.Services;
    using BIA.Net.Common;
    using BIA.Net.Common.Helpers;
    using BIA.Net.MVC;
    using BIA.Net.MVC.Filter;
    using Business.CTO;
    using Business.DTO;
    using Business.Services;
    using Common.Resources.BIA.Net;
    using MVC.ViewModel.Site;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using static BIA.Net.Business.Services.AllServicesDTO;
    using static Common.Constants;

    /// <summary>
    /// Controller for Site Pages
    /// </summary>
    /// <seealso cref="$safeprojectname$.Controllers.BaseController" />
    [Authorize(Roles = RoleAdmin + "," + RoleSiteAdmin)]
    public class SiteController : BaseController
    {
        /// <summary>
        /// the service site
        /// </summary>
        private readonly ServiceSite serviceSite;

        /// <summary>
        /// Initializes a new instance of the <see cref="SiteController"/> class.
        /// </summary>
        public SiteController()
        {
            serviceSite = BIAUnity.Resolve<ServiceSite>();
        }

        /// <summary>
        /// Index View : list all Sites.
        /// </summary>
        /// <returns>ActionResult : Index View</returns>
        [Authorize(Roles = RoleAdmin + "," + RoleSiteAdmin)]
        public ActionResult Index()
        {
            // Return the list of the site with the appropriate filter
            return View(GetListData(null, true));
        }

        /// <summary>
        /// Filter View.
        /// </summary>
        /// <returns>ActionResult : Filter view</returns>
        public ActionResult AdvancedFilter()
        {
            return View(PrepareFilterRelatedLink(serviceSite.GetAll(ServiceAccessMode.Write).OrderBy(s => s.Title).ToList()));
        }

        /// <summary>
        /// _List Partial View.
        /// </summary>
        /// <param name="advancedFilter">Advanced Filter</param>
        /// <returns>ActionResult : _List partial view</returns>
        public ActionResult _List(SiteAdvancedFilterCTO advancedFilter)
        {
            return PartialView(GetListData(advancedFilter));
        }

        /// <summary>
        /// Function to retrieve the site with the filter panel associated
        /// </summary>
        /// <param name="advancedFilter">List of filter</param>
        /// <param name="useDefaultView">boolean to force default view</param>
        /// <returns>Return the list of the sites</returns>
        public IEnumerable<SiteDTO> GetListData(SiteAdvancedFilterCTO advancedFilter = null, bool useDefaultView = false)
        {
            PrepareView("SiteTable", ref advancedFilter, useDefaultView);
            List<SiteDTO> listDTO = AllServicesDTO.GetAdvancedFiltered<SiteDTO, SiteAdvancedFilterCTO>(advancedFilter, ServiceAccessMode.Write);
            return listDTO;
        }

        /// <summary>
        /// Details View.  (ex :Site>/Details/5)
        /// </summary>
        /// <param name="id">The id of the Site.</param>
        /// <returns>ActionResult : Details View</returns>
        [Authorize(Roles = RoleAdmin + "," + RoleSiteAdmin)]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            SiteDTO siteDTO = serviceSite.Find(id);
            if (siteDTO == null)
            {
                return HttpNotFound();
            }

            return View("Details", BIASettingsReader.GetDialogLayout("PopupInfos"), siteDTO);
        }

        /// <summary>
        /// Create View for a Site  (ex : Site/Create)
        /// </summary>
        /// <returns>ActionResult : Create View</returns>
        [Authorize(Roles = RoleAdmin)]
        public ActionResult Create()
        {
            PrepareRelatedLink();
            return View();
        }

        /// <summary>
        /// Creates the specified site.
        /// </summary>
        /// <param name="siteDTO">The site.</param>
        /// <returns>ActionResult : Create View or Index View if success</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PreventDuplicateRequest]
        [Authorize(Roles = RoleAdmin)]
        public ActionResult Create([Bind(Include = "Id,Title,MembersIds")] SiteDTO siteDTO)
        {
            if (ModelState.IsValid)
            {
                serviceSite.Insert(siteDTO);
                return RedirectToAction("Index").Success(TextResources.CreatedSuccessfully);
            }

            PrepareRelatedLink();
            return View(siteDTO);
        }

        /// <summary>
        /// Edit View. (ex : Site/Edit/5)
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>ActionResult : Edit view</returns>
        [Authorize(Roles = RoleAdmin + "," + RoleSiteAdmin)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            SiteDTO siteDTO = serviceSite.Find(id);
            if (siteDTO == null)
            {
                return HttpNotFound();
            }

            PrepareRelatedLink();
            return View("Edit", BIASettingsReader.GetDialogLayout("PopupInfos"), siteDTO);
        }

        /// <summary>
        /// Edits the specified site.
        /// </summary>
        /// <param name="siteDTO">The site.</param>
        /// <returns>ActionResult : Edit view or Index View if success</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PreventDuplicateRequest]
        [Authorize(Roles = RoleAdmin + "," + RoleSiteAdmin)]
        public ActionResult Edit([Bind(Include = "Id,Title")] SiteDTO siteDTO)
        {
            if (ModelState.IsValid)
            {
                serviceSite.UpdateValues(siteDTO, new List<string>() { nameof(SiteDTO.Title) });
                return RedirectToAction("Index").Success(TextResources.UpdatedSuccessfully);
            }

            PrepareRelatedLink();
            return View("Edit", BIASettingsReader.GetDialogLayout("PopupInfos"), siteDTO);
        }

        /// <summary>
        /// Delete View. (ex : Site/Delete/5)
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>ActionResult : Delete view</returns>
        [Authorize(Roles = RoleAdmin)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            SiteDTO siteDTO = serviceSite.Find(id);
            if (siteDTO == null)
            {
                return HttpNotFound();
            }

            return View("Delete", BIASettingsReader.GetDialogLayout("PopupInfos"), siteDTO);
        }

        /// <summary>
        /// Deletes the specified site.
        /// </summary>
        /// <param name="id">The id of the site.</param>
        /// <returns>ActionResult : Delete view or Index View if success</returns>
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [PreventDuplicateRequest]
        [Authorize(Roles = RoleAdmin)]
        public ActionResult DeleteConfirmed(int id)
        {
            serviceSite.DeleteById(id);
            return RedirectToAction("Index").Success(TextResources.DeletedSuccessfully);
        }

        /// <summary>
        /// Releases unmanaged resources and optionally releases managed resources.
        /// </summary>
        /// <param name="disposing">true to release both managed and unmanaged resources; false to release only unmanaged resources.</param>
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        /// <summary>
        /// Prepares the related link.
        /// </summary>
        private void PrepareRelatedLink()
        {
        }

        /// <summary>
        /// Prepares the related link.
        /// </summary>
        /// <param name="listSiteDTO">list of site</param>
        /// <returns>the filter view Model</returns>
        private SiteAdvancedFilterVM PrepareFilterRelatedLink(List<SiteDTO> listSiteDTO)
        {
            SiteAdvancedFilterVM filterVM = new SiteAdvancedFilterVM
            {
                MslMember = new MultiSelectList(
                    listSiteDTO.SelectMany(s => s.Members.Select(m => m.DisplayName)).Distinct().ToList()),

                MslTitle = new MultiSelectList(
                    listSiteDTO.Select(s => s.Title).Distinct().ToList()),
            };
            return filterVM;
        }
    }
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Site/AdvancedFilter.cshtml
@model $safeprojectname$.ViewModel.Site.SiteAdvancedFilterVM

@using (Html.BeginForm("_List", "Site", FormMethod.Post, new { id = "SiteFilter", @class = "PreventDuplicateRequest form-horizontal" }))
{
    <div class="filter-box">
        <div class="form-group">
            @Html.T_Label("Title", htmlAttributes: new { @class = "control-label" })
            <div class="field">
                @Html.MultiselectFilter("filterTitle", (IEnumerable<SelectListItem>)Model.MslTitle, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.T_Label("Member", htmlAttributes: new { @class = "control-label" })
            <div class="field">
                @Html.MultiselectFilter("filterMember", (IEnumerable<SelectListItem>)Model.MslMember, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
    </div> <!-- all datatables fields are included in the input-box div -->
    <div class="row mt-4">
        <div class="btn-action">
            <button type="button" class="btn btn-second" onclick="BIA.Net.Filter.Action.ResetFilter('#SiteFilterContent','#SiteTable', BIA.Net.DataTable.LoadingType.Standard);">@TextResources.Reset</button>
        </div>
        <div class="btn-action">
            <button type="button" class="btn btn-main btn-filter" onclick="BIA.Net.DataTable.RefreshList('#SiteTable', BIA.Net.DataTable.LoadingType.Standard);">@TextResources.Filter</button>
        </div>
    </div>
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Site/Create.cshtml
@model $companyName$.$saferootprojectname$.Business.DTO.SiteDTO

@{
    ViewBag.Title = TextResources.Create + " " + TextResources.Site;
}

<h2>@TextResources.Create @TextResources.Site</h2>


@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "SiteCreateForm", @class = "PreventDuplicateRequest" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "err" })
    <div class="form-group">
        @Html.T_LabelFor(model => model.Title, htmlAttributes: new { @class = "bmd-label-floating mandatory" })
        <div class="field">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger bmd-help" })
        </div>
    </div>
</div>

}

@section Buttons {
    <div class="btn-action-container">
        <div class="btn-action">
            <button type="button" onclick="location.href='@Url.Action("Index")'" class="btn btn-second">@TextResources.Cancel</button>
        </div>
        <div class="btn-action">
            <button onclick="$('#SiteCreateForm').submit();" class="btn btn-main">@TextResources.Create</button>
        </div>
    </div>
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Site/Delete.cshtml
@model $companyName$.$saferootprojectname$.Business.DTO.SiteDTO

@{
    ViewBag.Title = TextResources.Delete + " " + TextResources.Site;
}

<h2>@ViewBag.Title</h2>

<h4 class="text-center">@TextResources.AreYouSureDelete</h4>
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "err" })
    @Html.HiddenFor(model => model.Id)
    <div class="form-group">
        @Html.T_LabelFor(model => model.Title, htmlAttributes: new { @class = "bmd-label-floating" })
        <div class="field">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @readonly ="" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger bmd-help" })
        </div>
    </div>
</div>

<div class='dotted-title'>
    <h3>@TextResources.Member@Html.Raw("s")</h3>
    <div class="section-buttons">
        @Html.ActionLink(TextResources.New, "Create", "Member", new { SiteId = Model.Id }, new { @class = "btn btn-main float-right d-none", BIADialogLink = "Type:Modal" })
    </div>
</div>
<div class="form-group">
    <div BIADialogRefresh="Url:@Url.Action("_List","Member", new { SiteId=Model.Id });OnFormValidated:@Url.Action("Create","Member")|@Url.Action("Edit","Member")|@Url.Action("Delete","Member")" style="overflow: auto;">
        @{Html.RenderAction("_List", "Member", new { SiteId = Model.Id });}
    </div>
</div>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "SiteDeleteForm" + Model.Id, @class = "PreventDuplicateRequest" }))
{
    @Html.AntiForgeryToken()
}

@section Buttons {
    <div class="btn-action-container">
        <div class="btn-action">
            <button type="button" onclick="location.href='@Url.Action("Index")'" class="btn btn-second">@TextResources.Cancel</button>
        </div>
        <div class="btn-action">
            <button onclick="$('#SiteDeleteForm@(Model.Id)').submit();" class="btn btn-main">@TextResources.Delete</button>
        </div>
    </div>
}
@section Scripts {
    <script type="text/javascript">
        BIA.Net.DataTable.InitStandard('#MemberTable');
    </script>
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Site/Details.cshtml
@model $companyName$.$saferootprojectname$.Business.DTO.SiteDTO

@{
    ViewBag.Title = TextResources.Details + " " + TextResources.Site;
}

<h2>@ViewBag.Title</h2>

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "err" })
    @Html.HiddenFor(model => model.Id)
    <div class="form-group">
        @Html.T_LabelFor(model => model.Title, htmlAttributes: new { @class = "bmd-label-floating" })
        <div class="field">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger bmd-help" })
        </div>
    </div>
</div>

<div class='dotted-title'>
    <h3>@TextResources.Member@Html.Raw("s")</h3>
    <div class="section-buttons">
        @Html.ActionLink(TextResources.New, "Create", "Member", new { SiteId = Model.Id }, new { @class = "btn btn-main float-right d-none", BIADialogLink = "Type:Modal" })
    </div>
</div>
<div class="form-group">
    <div BIADialogRefresh="Url:@Url.Action("_List","Member", new { SiteId=Model.Id });OnFormValidated:@Url.Action("Create","Member")|@Url.Action("Edit","Member")|@Url.Action("Delete","Member")" style="overflow: auto;">
        @{Html.RenderAction("_List", "Member", new { SiteId = Model.Id });}
    </div>
</div>

@section Buttons {
    <div class="btn-action-container">
        <div class="btn-action">
            <button type="button" onclick="location.href='@Url.Action("Index")'" class="btn btn-second">@TextResources.BackToList</button>
        </div>
        <div class="btn-action">
            <button type="button" onclick="location.href='@Url.Action("Edit", new { id = Model.Id })'" class="btn btn-main">@TextResources.Edit</button>
        </div>
    </div>
}

@section Scripts {
    <script type="text/javascript">
        BIA.Net.DataTable.InitStandard('#MemberTable');
    </script>
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Site/Edit.cshtml
@model $companyName$.$saferootprojectname$.Business.DTO.SiteDTO

@{
    ViewBag.Title = TextResources.Edit + " " + TextResources.Site;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "SiteEditForm" + Model.Id, @class = "PreventDuplicateRequest" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "err" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.T_LabelFor(model => model.Title, htmlAttributes: new { @class = "bmd-label-floating mandatory" })
            <div class="field">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger bmd-help" })
            </div>
        </div>
    </div>
}

<div class='dotted-title'>
    <h3>@TextResources.Member@Html.Raw("s")</h3>
    <div class="section-buttons">
        @Html.ActionLink(TextResources.New, "Create", "Member", new { SiteId = Model.Id }, new { @class = "btn btn-main float-right", BIADialogLink = "Type:Modal" })
    </div>
</div>

<div class="form-group">
    <div BIADialogRefresh="Url:@Url.Action("_List","Member", new { SiteId=Model.Id });OnFormValidated:@Url.Action("Create","Member")|@Url.Action("Edit","Member")|@Url.Action("Delete","Member")" style="overflow: auto;">
        @{Html.RenderAction("_List", "Member", new { SiteId = Model.Id });}
    </div>
</div>


@section Buttons {
    <div class="btn-action-container">
        <div class="btn-action">
            <button type="button" onclick="location.href='@Url.Action("Index")'" class="btn btn-second">@TextResources.Cancel</button>
        </div>
        <div class="btn-action">
            <button onclick="$('#SiteEditForm@(Model.Id)').submit();" class="btn btn-main">@TextResources.Save</button>
        </div>
    </div>
}


@section Scripts {
    <script type="text/javascript">
        BIA.Net.DataTable.InitStandard('#MemberTable');
    </script>
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Site/Index.cshtml
@using Newtonsoft.Json
@model IEnumerable<$companyName$.$saferootprojectname$.Business.DTO.SiteDTO>

@{
    ViewBag.Title = TextResources.ListOf + " " + TextResources.Site + "s";
}

<div class="biaList">
    <div class="biaListContainer">
        <div class="biaListFilter">
            <div class="w-100 mb-4">
                <a class="btn btn-filterbox mb-0 biaListFilter-toggle-cross">
                    <div class="svgIcon cross-filter"></div>
                </a>
                <h3 class="align-middle d-inline">@TextResources.Filters</h3>
            </div>
            <div id="SiteFilterContent"></div>
        </div>
        <div class="biaListDisplay">
            <div class="row">
                <div class="col-md-6">
                    <a Id="SiteFilterButton" class="btn align-top btn-filterbox empty biaListFilter-toggle" data-toggle="tooltip" data-target="" data-placement="bottom" title="@TextResources.Filters">
                        <div class="svgIcon filter-box"><span class="badge badge-danger d-none"></span></div>
                    </a>
                    <h2 class="titlePage align-top">@TextResources.ListOf @TextResources.Site@Html.Raw("s")</h2>
                </div>
                <div class="col dt-buttons-group">
                    @if (User.IsInRole(Constants.RoleAdmin))
                    {
                        @Html.ActionLink(TextResources.New, "Create", new { }, new { @class = "btn btn-main float-right", BIADialogLink = "Type:Modal" })
                    }
                </div>
            </div>
            <div id="SiteList" BIADialogRefresh="OnlyEvent;OnFormValidated:@Url.Action("Create")|@Url.Action("Edit")|@Url.Action("Delete")|@Url.Action("Create","Member")|@Url.Action("Edit","Member")|@Url.Action("Delete","Member")">
                @Html.Partial("_List", Model)
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @Html.ScriptViewToApply("SiteTable")
    <script type="text/javascript">
        BIA.Net.DataTable.InitStandard2(
            new BIA.Net.DataTable.Parameter({
                tableId: "SiteTable",
                urlList: '@Url.Action("_List")',
                exportButtons: ['csv', 'excel'],
                advancedfilterId: "SiteFilter",
                advancedfilterButtonOpenId: "SiteFilterButton",
                advancedfilterContentPanelId: "SiteFilterContent",
                advancedfilterUrl: '@Url.Action("AdvancedFilter")',
                dataTableOptionAdditional: { fixedHeader: { header: true } }
            })
        );
    </script>
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Site/_List.cshtml
@model IEnumerable<$companyName$.$saferootprojectname$.Business.DTO.SiteDTO>

<table class="dataTable stripe table rowselectable nowrap" id="SiteTable">
    <thead>
        <tr>
            <th>
                @Html.T_DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.T_DisplayNameFor(model => model.Members)
            </th>
            <th class="biaListColAction">@TextResources.Actions</th>
        </tr>
    </thead>
    @{ var odd = false; }
    @foreach (var item in Model)
    {
        odd = !odd;
        <tr class="@(odd ? "odd": "even")">
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @{ if (item.Members != null)
                    {
                        var last = item.Members.LastOrDefault();
                        foreach (var subitem in item.Members)
                        {
                            @Html.DisplayFor(modelItem => subitem.DisplayName)
                            if (!subitem.Equals(last))
                            {@Html.Raw(";")}
                    }
                }
                }
            </td>
            <td>
                <div class="">
                    @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @data_toggle = "tooltip", @data_placement = "left", @title = TextResources.Edit, @class = "listAction fas fa-pencil-alt", BIADialogLink = "Type:Modal" })
                    @Html.ActionLink(" ", "Details", new { id = item.Id }, new { @data_toggle = "tooltip", @data_placement = "left", @title = TextResources.Details, @class = "listAction fas fa-list-ul", BIADialogLink = "Type:Modal" })
                    @if (User.IsInRole(Constants.RoleAdmin))
                    {
                        @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @data_toggle = "tooltip", @data_placement = "left", @title = TextResources.Delete, @class = "listAction fas fa-trash-alt", BIADialogLink = "Type:Modal" })
                    }
                </div>
            </td>
        </tr>
    }

</table>