NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Controllers/MemberController.cs
// <copyright file="MemberController.cs" company="ZZCompanyNameZZ">
// Copyright (c) ZZCompanyNameZZ. All rights reserved.
// </copyright>

namespace $safeprojectname$.Controllers
{
    using BIA.Net.Authentication.MVC;
    using BIA.Net.Business.Services;
    using BIA.Net.Common.Helpers;
    using BIA.Net.MVC;
    using BIA.Net.MVC.Filter;
    using BIA.Net.MVC.Utility;
    using Business.DTO;
    using Business.Services;
    using Common;
    using Common.Resources.BIA.Net;
    using MVC.Helpers;
    using MVC.ViewModel.Member;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using static BIA.Net.Business.Services.AllServicesDTO;

    /// <summary>
    /// Controller for Member Pages
    /// </summary>
    /// <seealso cref="$safeprojectname$.Controllers.BaseController" />
    [Authorize(Roles = Constants.RoleAdmin + "," + Constants.RoleSiteAdmin)]
    public class MemberController : BaseController
    {
        /// <summary>
        /// the service member
        /// </summary>
        private ServiceMember serviceMember;

        /// <summary>
        /// Initializes a new instance of the <see cref="MemberController"/> class.
        /// </summary>
        public MemberController()
        {
            this.serviceMember = BIAUnity.Resolve<ServiceMember>();
        }

        /// <summary>
        /// Index View : list all Members.
        /// </summary>
        /// <returns>ActionResult : Index View</returns>
        public ActionResult Index()
        {
            List<MemberDTO> listMemberDTO = serviceMember.GetAll(ServiceAccessMode.Write).OrderBy(s => s.User.DisplayName).ToList();
            return View(listMemberDTO);
        }

        /// <summary>
        /// Filter View.
        /// </summary>
        /// <returns>ActionResult : Filter view</returns>
        public ActionResult Filter()
        {
            List<MemberDTO> listMemberDTO = serviceMember.GetAll(ServiceAccessMode.Write).OrderBy(s => s.User.DisplayName).ToList();
            return View(PrepareFilterRelatedLink(listMemberDTO));
        }

        /// <summary>
        /// _List Partial View.
        /// </summary>
        /// <param name="filterMember">members selected in filter</param>
        /// <param name="filterMemberRole">member roles selected in filter</param>
        /// <param name="siteId">The site identifier.</param>
        /// <returns>ActionResult : _List partial view</returns>
        public ActionResult _List(ICollection<string> filterMember, ICollection<string> filterMemberRole, int? siteId)
        {
            IEnumerable<MemberDTO> listMemberDTO = serviceMember.GetAllFromSite(siteId).OrderBy(m => m.DisplayName);
            if (filterMember != null || filterMemberRole != null)
            {
                if (filterMemberRole != null)
                {
                    listMemberDTO = listMemberDTO.Where(m => m.MemberRole.Any(mr => filterMemberRole.Contains(mr.Title)));
                }

                if (filterMember != null)
                {
                    listMemberDTO = listMemberDTO.Where(m => filterMember.Contains(m.DisplayName));
                }
            }

            return PartialView(listMemberDTO);
        }

        /// <summary>
        /// Details View.
        /// </summary>
        /// <param name="id">The id of the Member.</param>
        /// <returns>ActionResult : Details View</returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MemberDTO memberDTO = serviceMember.Find(id);
            if (memberDTO == null)
            {
                return HttpNotFound();
            }

            return View(memberDTO);
        }

        /// <summary>
        /// Create View for a Member.
        /// </summary>
        /// <param name="siteId">The site identifier.</param>
        /// <returns>ActionResult : Create View</returns>
        public ActionResult Create(int siteId)
        {
            PrepareRelatedLink(siteId);
            MemberDTO memberDTO = new MemberDTO
            {
                SiteId = siteId
            };
            return View(memberDTO);
        }

        /// <summary>
        /// Creates the specified member.
        /// </summary>
        /// <param name="memberDTO">The member.</param>
        /// <returns>ActionResult : Create View or Site Edit view if success</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PreventDuplicateRequest]
        public ActionResult Create([Bind(Include = "Id,UserId,MemberRoleIds,SiteId")] MemberDTO memberDTO)
        {
            if (ModelState.IsValid)
            {
                MemberDTO memberCreated = serviceMember.Insert(memberDTO);
                RefreshRolesAnotherConnectedMember(memberCreated);
                return RedirectToAction("CloseDialog", "DialogBasicAction", null).Success(TextResources.CreatedSuccessfully);
            }

            PrepareRelatedLink(memberDTO.SiteId);
            return View(memberDTO);
        }

        /// <summary>
        /// Edit View.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>ActionResult : Edit view</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MemberDTO memberDTO = serviceMember.Find(id);
            if (memberDTO == null)
            {
                return HttpNotFound();
            }

            PrepareRelatedLink(memberDTO.SiteId, memberDTO.Id);
            return View(memberDTO);
        }

        /// <summary>
        /// Edits the specified member.
        /// </summary>
        /// <param name="memberDTO">The member.</param>
        /// <returns>ActionResult : Edit view or Site Edit if success</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PreventDuplicateRequest]
        public ActionResult Edit([Bind(Include = "Id,SiteId,UserId,MemberRoleIds")] MemberDTO memberDTO)
        {
            ValidatorUtility.ValidOnly(ModelState, "Id,MemberRole");
            if (ModelState.IsValid)
            {
                MemberDTO memberUpdated = serviceMember.UpdateValues(memberDTO, new List<string>() { nameof(MemberDTO.User), nameof(MemberDTO.MemberRole) });
                RefreshRolesAnotherConnectedMember(memberUpdated);
                return RedirectToAction("CloseDialog", "DialogBasicAction", null).Success(TextResources.UpdatedSuccessfully);
            }

            PrepareRelatedLink(null);
            return View(memberDTO);
        }

        /// <summary>
        /// Delete View.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>ActionResult : Delete view</returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MemberDTO memberDTO = serviceMember.Find(id);
            if (memberDTO == null)
            {
                return HttpNotFound();
            }

            return View(memberDTO);
        }

        /// <summary>
        /// Deletes the specified member.
        /// </summary>
        /// <param name="id">The id of the member.</param>
        /// <returns>ActionResult : Delete view or Site Edit if success</returns>
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [PreventDuplicateRequest]
        public ActionResult DeleteConfirmed(int id)
        {
            MemberDTO memberDTO = serviceMember.Find(id);
            if (memberDTO == null)
            {
                return HttpNotFound();
            }

            RefreshRolesAnotherConnectedMember(memberDTO);
            serviceMember.DeleteById(id);
            return RedirectToAction("CloseDialog", "DialogBasicAction", null).Success(TextResources.DeletedSuccessfully);
        }

        /// <summary>
        /// Releases unmanaged resources and optionally releases managed resources.
        /// </summary>
        /// <param name="disposing">true to release both managed and unmanaged resources; false to release only unmanaged resources.</param>
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        /// <summary>
        /// Prepares the related link.
        /// </summary>
        /// <param name="excludeSiteId">The exclude site identifier.</param>
        /// <param name="memberId">The id member to include in filter</param>
        private void PrepareRelatedLink(int? excludeSiteId, int? memberId = null)
        {
            if (excludeSiteId != null)
            {
                ViewBag.UserDTOId = new SelectList(
                    ((ServiceUser)AllServicesDTO.GetService<UserDTO>()).GetAllExcludeSite(excludeSiteId, memberId).OrderBy(s => s.DisplayFullName),
                    nameof(UserDTO.Id),
                    nameof(UserDTO.DisplayFullName));
            }

            ViewBag.MemberRoleDTOIds = new MultiSelectList(
                AllServicesDTO.GetAll<MemberRoleDTO>(),
                nameof(MemberRoleDTO.Id),
                nameof(MemberRoleDTO.Title));
        }

        /// <summary>
        /// Call this function if the action of the user impact another member right or properties stocked in UserInfo.
        /// </summary>
        /// <param name="memberCreated">The member.</param>
        private void RefreshRolesAnotherConnectedMember(MemberDTO memberCreated)
        {
            if (memberCreated.User != null)
            {
                BIAAuthorizationFilterMVC<UserInfoMVC, UserDTO>.RefreshUserRoles(memberCreated.User.Login);
            }

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Controllers/Shared/CommonController.cs
// <copyright file="CommonController.cs" company="ZZCompanyNameZZ">
// Copyright (c) ZZCompanyNameZZ. All rights reserved.
// </copyright>

namespace $safeprojectname$.Controllers.Shared
{
    using BIA.Net.Authentication.MVC.Controllers;
    using Business.DTO;
    using Business.Helpers;
    using Business.Services.Authentication;
    using Newtonsoft.Json;
    using System.Web.Mvc;

    /// <summary>
    /// Common controller for the whole application
    /// </summary>
    /// <seealso cref="System.Web.Mvc.Controller" />
    public class CommonController : CommonAuthentController<ServiceSynchronizeUser, UserInfo, UserDTO>
    {
        /// <summary>
        /// Changes the session language according to the language selected by user
        /// </summary>
        /// <param name="code">the theme to set</param>
        /// <returns>Empty Action Result</returns>
        [AllowAnonymous]
        [HttpPost]
        public ActionResult SetTheme(string code)
        {
            string sTheme = JsonConvert.DeserializeObject<string>(code);
            if (!string.IsNullOrEmpty(sTheme))
            {
                ((UserInfo)User).UserProfile["Theme"] = sTheme;
            }

            return new EmptyResult();
        }
    }
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Member/Create.cshtml
@model $companyName$.$saferootprojectname$.Business.DTO.MemberDTO

@{
    ViewBag.Title = TextResources.Create + " " + TextResources.Member;
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "MemberCreateForm", @class = "PreventDuplicateRequest" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.SiteId)
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.T_LabelFor(model => model.User, htmlAttributes: new { @class = "bmd-label-floating mandatory" })
            <div class="field">
                @Html.DropDownListFor(model => model.UserId, (IEnumerable<SelectListItem>)ViewBag.UserDTOId, htmlAttributes: new { @class = "form-control", @style= "display: inline;width: calc(100% - 40px);" })
                <img src="~/Images/Refresh-icon.png" onclick="BIA.Net.Dialog.DoActionAndRefresh($(this), '@Url.Action("RefreshUsersFromAD", "Common")')">
                @Html.ValidationMessageFor(model => model.UserId, @TextResources.PleaseSelect + Html.T_DisplayNameFor(m => m.User ) + ".", new { @class = "text-danger bmd-help" })
            </div>
        </div> 

        <div class="form-group">
            @Html.T_LabelFor(model => model.MemberRole, htmlAttributes: new { @class = "bmd-label-floating" })
            <div class="field">
                @Html.CheckBoxListFor(model => model.MemberRoleIds, (IEnumerable<SelectListItem>)ViewBag.MemberRoleDTOIds, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MemberRoleIds, @TextResources.PleaseSelect + Html.T_DisplayNameFor(m => m.MemberRole ) + ".", new { @class = "text-danger bmd-help" })
            </div>
        </div> 
    </div>
}

@section Buttons {
    <div class="btn-action-container">
        <div class="btn-action">
            <button type="button" onclick="location.href='@Url.Action("Edit", "Site", new { id = Model.SiteId })'" class="btn btn-second">@TextResources.Cancel</button>
        </div>
        <div class="btn-action">
            <button onclick="$('#MemberCreateForm').submit();" class="btn btn-main">@TextResources.Create</button>
        </div>
    </div>
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Member/Delete.cshtml
@model $companyName$.$saferootprojectname$.Business.DTO.MemberDTO

@{
    ViewBag.Title = TextResources.Delete + " " + TextResources.Member;
}

<h2>@ViewBag.Title</h2>

<h4 class="text-center">@TextResources.AreYouSureDelete</h4>
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "err" })
    <div class="form-group">
        @Html.T_LabelFor(model => model.User, htmlAttributes: new { @class = "bmd-label-floating" })
        <div class="field">
            @Html.EditorFor(model => model.User.Email, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            @Html.ValidationMessageFor(model => model.User.Email, "", new { @class = "text-danger bmd-help" })
        </div>
    </div>

    <div class="form-group">
        @Html.T_LabelFor(model => model.MemberRole, htmlAttributes: new { @class = "bmd-label-floating" })
        <div class="field">
            @{ if (Model.MemberRole != null)
                {
                    var last = Model.MemberRole.LastOrDefault();
                    foreach (var subitem in Model.MemberRole)
                    {
                        @Html.DisplayFor(model => subitem.Title)
                        if (!subitem.Equals(last))
                        {@Html.Raw(";")}
                }
            }
            }
        </div>
    </div>

    <div class="form-group">
        @Html.T_LabelFor(model => model.Site, htmlAttributes: new { @class = "bmd-label-floating" })
        <div class="field">
            @Html.DisplayFor(model => model.Site.Title)
        </div>
    </div>

    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "MemberDeleteForm" + Model.Id, @class = "PreventDuplicateRequest" }))
    {
        @Html.AntiForgeryToken()
    }
</div>

@section Buttons {
    <div class="btn-action-container">
        <div class="btn-action">
            <button type="button" onclick="location.href='@Url.Action("Edit", "Site", new { id = Model.SiteId })'" class="btn btn-second">@TextResources.Cancel</button>
        </div>
        <div class="btn-action">
            <button onclick="$('#MemberDeleteForm@(Model.Id)').submit();" class="btn btn-main">@TextResources.Delete</button>
        </div>
    </div>
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Member/Details.cshtml
@model $companyName$.$saferootprojectname$.Business.DTO.MemberDTO

@{
    ViewBag.Title = TextResources.Details + " " + TextResources.Member;
}

<h2>@ViewBag.Title</h2>

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "err" })
    <div class="form-group">
        @Html.T_LabelFor(model => model.User, htmlAttributes: new { @class = "bmd-label-floating" })
        <div class="field">
            @Html.EditorFor(model => model.User.Email, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            @Html.ValidationMessageFor(model => model.User.Email, "", new { @class = "text-danger bmd-help" })
        </div>
    </div>

    <div class="form-group">
        @Html.T_LabelFor(model => model.MemberRole, htmlAttributes: new { @class = "bmd-label-floating" })
        <div class="field">
            @{ if (Model.MemberRole != null)
                {
                    var last = Model.MemberRole.LastOrDefault();
                    foreach (var subitem in Model.MemberRole)
                    {
                        @Html.DisplayFor(model => subitem.Title)
                        if (!subitem.Equals(last))
                        {@Html.Raw(";")}
                }
            }
            }
        </div>
    </div>

    <div class="form-group">
        @Html.T_LabelFor(model => model.Site, htmlAttributes: new { @class = "bmd-label-floating" })
        <div class="field">
            @Html.DisplayFor(model => model.Site.Title)
        </div>
    </div>
</div>

@section Buttons {
    <div class="btn-action-container">
        <div class="btn-action">
            <button type="button" onclick="location.href='@Url.Action("Edit", "Site", new { id = Model.SiteId })'" class="btn btn-second">@TextResources.BackToList</button>
        </div>
        <div class="btn-action">
            <button type="button" onclick="location.href='@Url.Action("Edit", new { id = Model.Id })'" class="btn btn-main">@TextResources.Edit</button>
        </div>
    </div>
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Member/Edit.cshtml
@model $companyName$.$saferootprojectname$.Business.DTO.MemberDTO

@{
    ViewBag.Title = TextResources.Edit + " " + TextResources.Member;
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "MemberEditForm"+ Model.Id, @class = "PreventDuplicateRequest" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.SiteId)

    <div class="form-group">
        @Html.T_LabelFor(model => model.User, htmlAttributes: new { @class = "bmd-label-floating" })
        <div class="field">
            @Html.DropDownListFor(model => model.UserId, (IEnumerable<SelectListItem>)ViewBag.UserDTOId, htmlAttributes: new { @class = "form-control", @style = "display: inline;width: calc(100% - 40px);" })
            <img src="~/Images/Refresh-icon.png" onclick="BIA.Net.Dialog.DoActionAndRefresh($(this), '@Url.Action("RefreshUsersFromAD", "Common")')">
            @Html.ValidationMessageFor(model => model.UserId, @TextResources.PleaseSelect + Html.T_DisplayNameFor(m => m.User) + ".", new { @class = "text-danger bmd-help" })
        </div>
    </div>

    <div class="form-group">
        @Html.T_LabelFor(model => model.MemberRole, htmlAttributes: new { })
        <div class="field">
            @Html.CheckBoxListFor(model => model.MemberRoleIds, (IEnumerable<SelectListItem>)ViewBag.MemberRoleDTOIds, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MemberRoleIds, @TextResources.PleaseSelect + Html.T_DisplayNameFor(m => m.MemberRole) + ".", new { @class = "text-danger" })
        </div>
    </div>
</div>
}

@section Buttons {
    <div class="btn-action-container">
        <div class="btn-action">
            <button type="button" onclick="location.href='@Url.Action("Edit", "Site", new { id = Model.SiteId })'" class="btn btn-second">@TextResources.Cancel</button>
        </div>
        <div class="btn-action">
            <button onclick="$('#MemberEditForm@(Model.Id)').submit();" class="btn btn-main">@TextResources.Save</button>
        </div>
    </div>
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Member/Filter.cshtml
@model $safeprojectname$.ViewModel.Member.MemberFilterVM

@using (Html.BeginForm("_List", "Member", FormMethod.Post, new { id = "MemberFilter", @class = "PreventDuplicateRequest form-horizontal" }))
{
    <div class="filter-box">
        <div class="form-group">
            @Html.T_Label("User", htmlAttributes: new { @class = "control-label" })
            <div class="field">
                @Html.MultiselectFilter("filterMember", (IEnumerable<SelectListItem>)Model.MslMember, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.T_Label("MemberRole", htmlAttributes: new { @class = "control-label" })
            <div class="field">
                @Html.MultiselectFilter("filterMemberRole", (IEnumerable<SelectListItem>)Model.MslMemberRole, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
    </div> <!-- all datatables fields are included in the input-box div -->
    <div class="row mt-4">
        <div class="btn-action">
            <button type="button" class="btn btn-second" onclick="BIA.Net.Filter.Action.ResetFilter('#MemberFilterContent','#MemberTable', BIA.Net.DataTable.LoadingType.Standard);">@TextResources.Reset</button>
        </div>
        <div class="btn-action">
            <button type="button" class="btn btn-main btn-filter" onclick="BIA.Net.DataTable.RefreshList('#MemberTable', BIA.Net.DataTable.LoadingType.Standard);">@TextResources.Filter</button>
        </div>
    </div>
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Member/Index.cshtml
@model IEnumerable<$companyName$.$saferootprojectname$.Business.DTO.MemberDTO>

@{
    ViewBag.Title = TextResources.ListOf + " " + TextResources.Member + "s";
}

<!-- start Sidebar -->
<div class="biaList">
    <div class="biaListContainer">
        <div class="biaListFilter">
            <div class="w-100 mb-4">
                <a class="btn btn-filterbox mb-0 biaListFilter-toggle-cross">
                    <div class="svgIcon cross-filter"></div>
                </a>
                <h3 class="align-middle d-inline">@TextResources.Filters</h3>
            </div>
            <div id="MemberFilterContent"></div>
        </div>
        <!-- end Sidebar -->
        <div class="biaListDisplay">
            <div class="row">
                <div class="col-md-6">
                    <a Id="MemberFilterButton" class="btn align-top btn-filterbox empty biaListFilter-toggle" data-toggle="tooltip" data-target="" data-placement="bottom" title="@TextResources.Filters">
                        <div class="svgIcon filter-box"><span class="badge badge-danger d-none"></span></div>
                    </a>
                    <h2 class="titlePage align-top">@TextResources.ListOf @Html.TranslateAndPlurialize("Member")</h2>
                </div>
                <div class="col dt-buttons-group">
                    @Html.ActionLink(TextResources.New, "Create", new { }, new { @class = "btn btn-main float-right", BIADialogLink = "Type:Modal" })
                </div>
            </div>
            <div id="MemberList" BIADialogRefresh="OnlyEvent;OnFormValidated:@Url.Action("Create")|@Url.Action("Edit")|@Url.Action("Delete")">
                @Html.Partial("_List", Model)
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script type="text/javascript">
        BIA.Net.DataTable.InitStandard('#MemberTable', '@Url.Action("_List")', null, "#MemberFilter");
        BIA.Net.Filter.Action.LoadFilterWhenOpen("#MemberFilterButton", "#MemberFilterContent", '@Url.Action("Filter")');
    </script>
}

NetFramework/VisualStudioComponents/BIAProjectCreator/Main/ZZProjectKit/Temp/MVC/Views/Member/_List.cshtml
@model IEnumerable<$companyName$.$saferootprojectname$.Business.DTO.MemberDTO>


<table class="dataTable stripe table @*rowselectable*@" id="MemberTable">
    <thead>
        <tr>
            <th>
                @Html.T_DisplayNameFor(model => model.User)
            </th>

            <th>
                @Html.T_DisplayNameFor(model => model.MemberRole)
            </th>
            <th class="biaListColAction">@TextResources.Actions</th>
        </tr>
    </thead>
    @{ var odd = false; }
    @foreach (var item in Model)
    {
        odd = !odd;
    <tr class="@(odd ? "odd": "even")">
        <td>
            @Html.DisplayFor(modelItem => item.User.DisplayFullName)
            @if (!item.User.DAIEnable)
            {
                <span style="color: red;">(Not in AD user group)</span>
            }
        </td>
        <td>
            @{ if (item.MemberRole != null)
                {
                    var last = item.MemberRole.LastOrDefault();
                    foreach (var subitem in item.MemberRole)
                    {
                        @Html.DisplayFor(modelItem => subitem.Title)
                        if (!subitem.Equals(last))
                        {@Html.Raw(";")}
                }
            }
            }
        </td>
        <td>
            @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @data_toggle = "tooltip", @data_placement = "left", @title = TextResources.Edit, @class = "fas fa-pencil-alt", BIADialogLink = "Type:Modal" })
            @Html.ActionLink(" ", "Details", new { id = item.Id }, new { @data_toggle = "tooltip", @data_placement = "left", @title = TextResources.Details, @class = "fas fa-list-ul", BIADialogLink = "Type:Modal" })
            @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @data_toggle = "tooltip", @data_placement = "left", @title = TextResources.Delete, @class = "fas fa-trash-alt", BIADialogLink = "Type:Modal" })
        </td>
    </tr>
    }

</table>